<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200511133443 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE cron_test_domain_model_country (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, iso VARCHAR(2) NOT NULL, klopotek VARCHAR(4) NOT NULL, region VARCHAR(255) NOT NULL, sorting INT NOT NULL, shipping_cost DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_8FB5F5005E237E06 (name), UNIQUE INDEX UNIQ_8FB5F50061587F41 (iso), UNIQUE INDEX UNIQ_8FB5F500569218BE (klopotek), INDEX sorting_idx (sorting), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cron_test_domain_model_order (persistence_object_identifier VARCHAR(40) NOT NULL, user LONGTEXT NOT NULL COMMENT \'(DC2Type:object)\', created DATETIME NOT NULL, billingaddress LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:object)\', deliveryaddress LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:object)\', paymentmethod VARCHAR(255) NOT NULL, paymentdata LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', status INT DEFAULT NULL, products LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:object)\', shipping DOUBLE PRECISION NOT NULL, voucher VARCHAR(255) DEFAULT NULL, customercomment LONGTEXT DEFAULT NULL, identifier VARCHAR(255) NOT NULL, id INT DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');

    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('DROP TABLE cron_test_domain_model_country');
        $this->addSql('DROP TABLE cron_test_domain_model_order');
    }
}
